### ISSUE TITLE
Application Bug: Book-to-book view (with chart) 

### ISSUE THREAD

**Issue by aslishah** [kitab-project-org/kitab-project-org.github.io#17]
**Relevant application (delete as appropriate)**
 Book-to-book view (with chart) 

**Describe the bug**
NoorLib files still don't show in the book to book alignment comparison. See the screenshot

**To Reproduce**

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/32569404/106597467-6027af00-654e-11eb-8d34-c2b7ef86e1ee.png)

**How did you access the application:**
 - Browser: [Give browser and version]
 - URL: [if using browser]
 - Downloaded powerBI report: [Give version that you downloaded]

**Suggested fixes**
I believe this was supposed to be resolved last night. I am just reporting in case there is a bug. 

**Additional context**

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bug Report : Book-to-book view (with chart) #17 Noor-Lib files](https://trello.com/c/DOzDtHeB/13-bug-report-book-to-book-view-with-chart-17-noor-lib-files)

**Comment by sohailmerchant** [comment]
This is fixed now.  I tested this with Noorlib0007682-JK000778 and it is working fine.  Generally, when the book text is not showing it means it is not on the OpenITI imech repo
