### ISSUE TITLE
Add aggregated data to the metadata app

### ISSUE THREAD

**Issue by SarahKITAB** [kitab-project-org/kitab-project-org.github.io#19]
Can you please add to the KITAB internal metadata app. links for the aggregated data.

Now this is 2020 data. Ryan and Masoumeh are working on a new experimental aggregated data set. It would be great to put those up too when they are ready.

I asked Sohail to do this via email. Am formalising here because that is better.

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Add aggregated passim links to metadata search](https://trello.com/c/LeUnHvMi/15-add-aggregated-passim-links-to-metadata-search)

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Update:](https://trello.com/c/6msd624l/18-data-update)

**Comment by sohailmerchant** [comment]
This was made available on the app
