### ISSUE TITLE
Application Bug:  / Book-to-book view (with chart) / 

### ISSUE THREAD

**Issue by aslishah** [kitab-project-org/kitab-project-org.github.io#20]
**Relevant application (delete as appropriate)**
Book-to-book view (with chart)

**Describe the bug**

There seems to be a problem with the reuse files of Abu Bakr Maliki’s Riyad **(Shamela0148883-ara1.mARkdown)**. The visualizer works with other files but doesn’t recognize reuse files from al-Maliki’s Riyad. I checked the alignments format, they are not different from others. I also tried to change the extension, tried with small and larger files, still didn’t work.

**To Reproduce**
Try to visualise any reuse file from **(Shamela0148883-ara1.mARkdown)**. 

**Expected behaviour**
It should be abe to visualise the files since it works on others without a problem. I haven't encountered problem with other files since the last fix apart from reading NoorLib files in the Reader and visualising extra-large files. 

**Screenshots**
![image](https://user-images.githubusercontent.com/32569404/106901288-7751d280-66ef-11eb-9621-eb5f2aab90c9.png)

**How did you access the application:**
 - Browser: [Chrome]
 - URL: [https://pairwise-viz-v6.azurewebsites.net/visualise]
 - Downloaded powerBI report: [NA]
 - Version [October. Reuse files, last updated: Jan 17 2021]

**Suggested fixes**
Do you propose any fixes to this issue?

**Additional context**

**Comment by mabarber92** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Data Update: Issue with Shamela0148883-ara1.mARkdown](https://trello.com/c/EkRXlt2O/16-data-update-issue-with-shamela0148883-ara1markdown)

**Comment by aslishah** [comment]
Hi Mathew, do  I get an automatic Trello account with my Github account? Do
I need one?

Best wishes,
Aslisho

**Comment by mabarber92** [comment]
@aslishah It seems that this version ID is missing from the metadata. Could you check if the URI/ID was changed?

**Comment by aslishah** [comment]
@Mathew Barber <Mathew.Barber@aku.edu> thank you so much for looking at it.
Yes, indeed the URI has been changed. It is not longer Shamela, but
Sham19Y. I changed the file name and it worked perfectly. Perhaps it is not
too difficult to change the file names on the repository, but for now this
works fine for me.

Best wishes,
Aslisho

**Comment by mabarber92** [comment]
Great! Thanks for checking!

**Comment by aslishah** [comment]
No worries. The Visualisation App's alignment reader and Book view stopped working though. There is another issue for this, but I don't know when are those going to be resolved.
