### ISSUE TITLE
Application Bug: Metadata App

### ISSUE THREAD

**Issue by mabarber92** [kitab-project-org/kitab-project-org.github.io#25]
**Relevant application (delete as appropriate)**
Metadata App

**Describe the bug**
When accessing link to passim stats from the metadata app for the book: Hindawi95926405Vols-ara1.completed,

the app creates the folllowing link:

http://dev.kitab-project.org/passim01022021/Hindawi95926405-ara1.completed/

The correct link on the server is:

http://dev.kitab-project.org/passim01022021/Hindawi95926405Vols-ara1.completed/

**Comment by mabarber92** [comment]
@pverkind I've not fed this issue onto the trello board I am using for the apps, as I think you'll probably just push a fix yourself fairly quickly? If you want me to track it through the trello, just let me know and I'll link it up.

**Comment by pverkind** [comment]
I will! Thanks for notifying me

**Comment by pverkind** [comment]
Solved now!

**Comment by sohailmerchant** [comment]
This is resolved.
