### ISSUE TITLE
Application Bug: Pairwise Book Visualisation

### ISSUE THREAD

**Issue by aslishah** [kitab-project-org/kitab-project-org.github.io#34]
**Relevant application (delete as appropriate)**
 Book-to-book view (with chart) - the Pairwise visualisation "V2" doesn't work.

**Describe the bug**
When you upload a csv file it says "this page doesn't exist"

**To Reproduce**
1. Go to 'the App'
2. Click on "choose file"
3. Click on "Upload"

**Expected behavior**
To show the spaggetti monster

**Screenshots**

**How did you access the application:**
 - Browser: [Chrome]
 - URL: [https://pairwise-viz-v6.azurewebsites.net/visualise]
 - Downloaded powerBI report: NA
 - Version [V2]

**Suggested fixes**
Do you propose any fixes to this issue?

**Additional context**

**Comment by sohailmerchant** [comment]
This has been fixed.
