### ISSUE TITLE
Application Bug: Pairwise Book Visualisation

### ISSUE THREAD

**Issue by mabarber92** [kitab-project-org/kitab-project-org.github.io#48]
**Relevant application (delete as appropriate)**
 Book-to-book view (with chart) - new vers

**Describe the bug**
Milestone number for the two text views is showing total number of ms in each work rather than the actual ms. See below screenshot:

![image](https://github.com/kitab-project-org/kitab-project-org.github.io/assets/46000359/feb72896-b5fd-4d60-9f12-d0f4a78e199c)

The ms numbers in the blue tooltip are the correct ones. The ms numbers in the boxes below are the total number of ms in each work.

**Comment by sohailmerchant** [comment]
This is fixed now. @mabarber92
